app = "interview-tracker"
primary_region = "ams"

[build]

[env]
  PORT = "8080"
  DATABASE_URL = "sqlite:////data/jobs.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "interview_data"
  destination = "/data"
